#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
    command: bash -c "python /code/mysite/manage.py migrate --no-input && python /code/mysite/manage.py runserver 0.0.0.0:8000"
