# Generated by Django 3.1.1 on 2020-11-05 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(default='New Document', max_length=240)),
                ('uploadDate', models.DateField(auto_now_add=True)),
                ('editDateTime', models.DateTimeField(auto_now=True)),
                ('contents', models.CharField(max_length=8192)),
                ('public', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_set', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(related_name='editors_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
